#### general settings
name: us_fre_doubledeg
use_tb_logger: false
model: FreDegSRModel
scale: 4
gpu_ids: [0]
metrics: [niqe, pi, musiq]

#### datasets
datasets:
  train:
    name: us
    mode: FreUnPairedDataset
    data_type: lmdb
    color: RGB
    ratios: [50, 200]

    dataroot_tgt: /home/ps/zhencunjiang/US_sr/us_data/us_train_hr.lmdb
    dataroot_src: /home/ps/zhencunjiang/US_sr/us_data/us_train_lr.lmdb

    use_shuffle: true
    workers_per_gpu: 0  # per GPU
    imgs_per_gpu: 32
    tgt_size: 256
    src_size: 256
    use_flip: true
    use_rot: true

  val:
    name: us
    mode: SingleImageDataset
    data_type: lmdb
    color: RGB

    dataroot: /home/ps/zhencunjiang/US_sr/us_data/us_val_lr.lmdb

#### network structures
networks:
  netDeg:
    which_network: FreDegModel
    setting:
      scale: 4
      nc_img: 3
      kernel_opt:
        mix: False
          spatial: False
          nc: 3
          nf: 64
          nb: 8
          head_k: 1
          body_k: 1
          ksize: 21
          zero_init: True
      noise_opt:
         spatial: False
          nc: 3
          nf: 32
          nb: 8
          head_k: 3
          body_k: 3
          dim: 1
          zero_init: False
    pretrain:
      path: ~
      strict_load: true

  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 3
      nf: 64
      nb: 3
      stride: 2
    pretrain:
      path: ~
      strict_load: true

#  netD2:
#    which_network: PatchGANDiscriminator
#    setting:
#      in_c: 3
#      nf: 64
#      nb: 3
#      stride: 1
#    pretrain:
#      path: ~
#      strict_load: true

  netSR:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain:
      path: ~
      strict_load: False
#### training settings: learning rate scheme, loss
train:
  resume_state: ~

  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0
  optim_deg: true
  optim_sr: true

  losses:
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 1.0

    sr_pix_sr:
      type: L1Loss
      weight: 1.0

    noise_mean:
      type: MSELoss
      weight: 1.0

#    cycle_loss:
#      type: redegloss
#      weight: 0.1

#    sr_adv:
#      type: GANLoss
#      gan_type: lsgan
#      real_label_val: 1.0
#      fake_label_val: 0.0
#      weight: !!float 0.05

    sr_percep:
      type: PerceptualLoss
      layer_weights:
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      weight: !!float 0.05

  optimizers:
    netDeg:
      type: Adam
      lr: !!float 2e-4
    netD1:
      type: Adam
      lr: !!float 2e-4
    netSR:
        type: Adam
        lr: !!float 2e-4
#    netD2:
#        type: Adam
#        lr: !!float 2e-4

  niter: 200000
  warmup_iter: -1  # no warm up

  schedulers:
    default:
      type: MultiStepRestartLR
      milestones: [50000, 100000, 150000]
      gamma: 0.5

  manual_seed: 0
  val_freq: 200000

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

